### ISSUE TITLE
Views Panel: Multiple Series Visualisations (Bar, Line)

### ISSUE THREAD

**Issue by pwalsh** [openspending/os-viewer#4]
# Description

Essentially, we are building visualisations using D3. And, for basic visualisations, we have two broad types:

* single series visualisations #3
* multiple series visualisations (this)

For each type, the current state of the data will need to be further processed into the specific shape required for a given visualisation. This processed version is very specific to the particular component rendering the visualisation, and therefore we do not need to keep this further modified data presentation in our state tree. 

For example, in the current Treemap, we do this [final processing in the component](https://github.com/openspending/fiscal-data-package-viewer/blob/master/src/scripts/components/views/Treemap.js#L8), using a function that produces the input a [D3 Treemap expects](https://github.com/openspending/fiscal-data-package-viewer/blob/master/src/scripts/utils/index.js#L9). 

We'd need to implement a similar pattern for multiple series visualisations, such as [line charts](https://reactiva.github.io/react-d3-website/).

# Tasks

* [ ] Add an additional two tabs to the tabbed visualisations, one for a bar chart and one for a line chart 
* [ ] Write a generic `dataToMultipleSeries` function for processing the current data state to that required for such views, and implement it as part of the view component
* [ ] Write tests for the component that renders each view
* [ ] Write tests for the `dataToMultipleSeries` function

**Comment by pwalsh** [comment]
N/A
