### ISSUE TITLE
Geo View

### ISSUE THREAD

**Issue by pwalsh** [openspending/os-viewer#57]
# Description

Some data in OpenSpending has a `location` dimension. Combined with the `countryCode` of Fiscal Data Package, we can use this dimension to get a GeoJSON object for the region from an appropriate server, and cast the fiscal information onto a map.

As we have a plan to refactor [babbage.ui into a set of modular components](https://github.com/openspending/babbage.ui/issues/16), I suggest that we implement this Geo View according to the desired pattern for a Babbage component. This can then serve as a template for the refactor over there, and also as a demonstrator of how things will look.

Also refer to http://index.okfn.org for some directions on UI/X we implemented there for similar goals.

# Tasks

Below describes a first iteration. Let's get something working and then do another iteration to work on UX specifics, as a standalone component, and also how this works in relation to rest of Viewer.

* [x] Choose a lib to render the GeoJSON - leaflet.js is possible, but we probably will never need all the features there, so I suggest we just use D3 ( http://bost.ocks.org/mike/map/ )
* [x] Two conditions need to be met in order to show a Geo View at all:
  * The FDP has a `countryCode`
  * The model has a `location` dimension
  * We can query a server with the `countryCode` and get back a GeoJSON object. Cosmopolitan will support this: `/geojson/country/{id}`, but for now we should mock this service and in the background just get the Moldova GeoJSON directly from here: https://raw.githubusercontent.com/openspending/fiscal-data-package-demos/master/boost-moldova/data/boost-moldova.geojson
* [x] View is populated by an aggregate query on the location dimension
* [x] Hover on an area shows a short preview of the data based on current filters
* [x] Click drills in to an area, and shows a "card" that has more info for the area (see index.okfn.org for reference)
* [x] Tests

**Comment by pwalsh** [comment]
@akariv 

See above which is the spec @kravets-levko has to work with to implement a geovis. 

Levko's question was/is:

    I need you to explain me some things about API. In FDP Viewer app most of operations are performed using model from your API. But now I need to perform some actions when user selects dimension that originally (in FDP) has type `location`. I don't understand how to map them. Say, I have both datapackage object and model object, and also I've found `location` dimensions in FDP. How can I find the same dimensions in model?

This maybe be related to the general issues I see in the Viewer app when consuming the API, and expressed for dimensions in #63

**Comment by akariv** [comment]
Hey @kravets-levko , please see #63 for instructions which should answer this question.
