### ISSUE TITLE
Accept package identifier as url param

### ISSUE THREAD

**Issue by pwalsh** [openspending/os-viewer#58]
# Description

Currently, it is only possible to get to a particular package using the selector in the UI. We want to be able to get directly to a given package by passing an identifier for that package as a URL param.

# Tasks

* [x] Add support for URL params: `{viewer_domain}/:id`
  * [x] Selects the right package in the select box on the UI
  * [x] Changing a package in the select box UI updates the URL too
* [x] Unit tests

**Comment by pwalsh** [comment]
@kravets-levko @borysyuk tests?
